// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: kmessage.proto

package treeinterface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Parent   []byte `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Metadata []byte `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *Operation) Reset() {
	*x = Operation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kmessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_kmessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_kmessage_proto_rawDescGZIP(), []int{0}
}

func (x *Operation) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Operation) GetParent() []byte {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Operation) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_kmessage_proto protoreflect.FileDescriptor

var file_kmessage_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x6b, 0x74, 0x72, 0x65, 0x65, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x46, 0x65, 0x6c, 0x69, 0x78, 0x57, 0x68, 0x69, 0x74, 0x65, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x2f, 0x54, 0x72, 0x65, 0x65, 0x2d, 0x43, 0x52, 0x44, 0x54, 0x73, 0x2d, 0x57, 0x69, 0x74,
	0x68, 0x2d, 0x4d, 0x6f, 0x76, 0x65, 0x2f, 0x74, 0x72, 0x65, 0x65, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kmessage_proto_rawDescOnce sync.Once
	file_kmessage_proto_rawDescData = file_kmessage_proto_rawDesc
)

func file_kmessage_proto_rawDescGZIP() []byte {
	file_kmessage_proto_rawDescOnce.Do(func() {
		file_kmessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_kmessage_proto_rawDescData)
	})
	return file_kmessage_proto_rawDescData
}

var file_kmessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kmessage_proto_goTypes = []interface{}{
	(*Operation)(nil), // 0: ktree.Operation
}
var file_kmessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kmessage_proto_init() }
func file_kmessage_proto_init() {
	if File_kmessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kmessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Operation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kmessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kmessage_proto_goTypes,
		DependencyIndexes: file_kmessage_proto_depIdxs,
		MessageInfos:      file_kmessage_proto_msgTypes,
	}.Build()
	File_kmessage_proto = out.File
	file_kmessage_proto_rawDesc = nil
	file_kmessage_proto_goTypes = nil
	file_kmessage_proto_depIdxs = nil
}
